api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    defaults:
        formats:
            json: ['application/json']
        requirements:
            _locale: en|fr
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
