fos_user: 
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "impactdev3@gmail.com"
    sender_name: "ImpactDev Admin"
  service:
    mailer: 'symfony.mailer'